version: '3.8'

services:

  santas-db:
    image: postgres
    environment: 
      POSTGRES_USER: "santa"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./db/:/var/lib/postgresql/data
    container_name: santas-db

  santas-crm:
    image: kosvi/santas_own_crm
    environment:
      PORT: 3000
      DATABASE_URL: "postgres://santa:password@santas-db:5432/santa"
      NODE_ENV: "production"
      SECRET: "my-secret-key"
    ports: 
      - 3000:3000
    container_name: santas-crm
    depends_on:
      - "santas-db"
