
GET http://localhost:3000/api/groups
Authorization: bearer <token>


###

DELETE http://localhost:3000/api/groups/5
Authorization: bearer <token>

###

GET http://localhost:3000/api/groups/foo


###

GET http://localhost:3000/api/groups/bar

###

POST http://localhost:3000/api/groups
Content-Type: application/json

{
  "name": "foo"
}

###

POST http://localhost:3000/api/groups/4
Content-Type: application/json

{
  "functionalityId": 2,
  "read": false,
  "write": false
}

###

POST http://localhost:3000/api/groups
Content-Type: application/json

{
  "foo": "bar"
}

###

POST http://localhost:3000/api/groups/4
Content-Type: application/json

{
  "functionalityId": 4,
  "read": "false",
  "write": false
}


###

PUT http://localhost:3000/api/groups/5
Content-Type: application/json
Authorization: bearer 

{
  "functionalityId": 5,
  "read": false,
  "write": false
}


###

GET http://localhost:3000/api/groups/functionalities
Content-Type: application/json
Authorization: bearer 


### 
POST http://localhost:3000/api/groups/connect
Content-Type: application/json
Authorization: bearer <token>

{
  "groupId": 4,
  "userId": 18
}