POST http://localhost:3000/api/users
Content-Type: application/json
Authorization: bearer <token>

{
  "username": "foo5",
  "password": "bar",
  "name": "Foo Bar"
}

###

GET http://localhost:3000/api/users/1
Content-Type: application/json
Authorization: bearer <token>


###

PUT http://localhost:3000/api/users/1
Content-Type: application/json
Authorization: bearer <token>

{
  "password": "santa"
}