name: Test Develop-branch

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
    types: [opened, synchronize]
  

jobs:
  test: 
    if: ${{ !contains(github.event.head_commit.message, '#skip') }}
    runs-on: ubuntu-20.04

    # Tests need Postgres, documentation for Github Actions / Postgres
    # https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: "santa"
          POSTGRES_USER: "santa"
          POSTGRES_PASSWORD: "password"
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: '14.x'
      # Install, lint and test backend
      - name: install backend
        run: CI=true npm install --prefix server
      - name: lint backend
        run: npm run lint --prefix server
      - name: test backend
        run: npm test --prefix server
        env:
          DATABASE_URL: "postgres://santa:password@localhost:5432/santa"
          NODE_ENV: "test"
          SECRET: "token-sign-secret"
      # Install, lint and test frontend
      - name: install frontend
        run: npm install --prefix client
      - name: lint frontend
        run: npm run lint --prefix client
      - name: test frontend
        run: npm test --prefix client
