name: Production jobs

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: '14.x'
      - name: install backend
        run: npm install --prefix server
      - name: lint backend
        run: npm run lint --prefix server
      - name: test backend
        run: npm test --prefix server
      - name: install frontend
        run: npm install --prefix client
      - name: lint frontend
        run: npm run lint --prefix client
      - name: test frontend
        run: npm test --prefix client
      - name: prepare backend for e2e-tests
        run: |
          cat << EOF > server/.env
          PORT=3001
          EOF
      - name: prepare frontend for building
        run: |
          cat << EOF > client/.env
          REACT_APP_API_BASE=http://localhost:3001/api/
          EOF
      - name: build frontend
        run: | 
          npm run build --prefix client
          mv client/build server
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run e2e --prefix client
          start: npm run dev
          wait-on: http://localhost:3001
          working-directory: ./server
      